demo1/urls.py
from django.urls import path
from demo1.views import *

urlpatterns = [
    path('index/', index, name = 'index'),
    path('index2/', index2, name = 'index2')
]

djangoModels/urls.py
from django.urls import path
from djangoModels.views import *

urlpatterns = [
    path("users/", getUsers, name="users"),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoRoute.views import *
from djangoTemplate.views import *

urlpatterns = [
    path("admin/", admin.site.urls),

    # 1. Using children route
    # path("djangoRoute/", include("djangoRoute.urls")),

    # 2. Using children route with namespace
    path("djangoRoute/", include(("djangoRoute.urls", "djangoRoute"), namespace="djangoRoute")),

    # The following are for django templates
    path("index/", djangoTemplateIndex),
    # Using children route (with namespace)
    # path("djangoModels/", include("djangoModels.urls"))
]

djangoRoute/urls.py
from django.urls import path, re_path
from djangoRoute.views import *

urlpatterns = [
    path('index/', index, name = 'index'),
    path('userlist/', user_list, name = 'userlist'),

    # passing one argument
    path('userdetail/<int:user_id>/', user_detail, name = 'userdetail'),

    # passing multiple arguments
    path('test/<int:a>/<int:b>', test, name = 'test'),

    # using regular expression
    re_path(r'test2/(?P<a>\d+)/(?P<b>\d+)/', test, name = 'test2'),


    # The following are examples of redirecting and reverse parsing through views
    path('myredirect/', my_redirect),
    path('touserlist/', redirect_to_user_list),
    path('touserdetail/', redirect_to_user_detail),
]

djangoModels/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=30, unique=True)  # name varchar(30)
    age = models.IntegerField(default=18)                # age int default 18
    is_deleted = models.BooleanField(default=False)


class PersonModel(models.Model):
    # Create customized primary key instead of relying on default
    uid = models.AutoField(auto_created=True, primary_key=True)

    # db_index is set to true to make the column index
    name = models.CharField(max_length=30, unique=True, db_index=True)  # name varchar(30)

    # Use default to set the age
    age = models.IntegerField(default=18)                # age int default 18

    # Use text field (make it optional)
    self_intro = models.TextField(null=True, blank=True)

    # Use decimals (limit the number of decimal digits to 2)
    height = models.DecimalField(max_digits=5, decimal_places=2, default=150.00)

    is_deleted = models.BooleanField(default=False)

djangoRoute/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=30, unique=True)  # name varchar(30)
    age = models.IntegerField(default=18)                # age int default 18
    is_deleted = models.BooleanField(default=False)

djangoTemplate/models.py
from django.db import models

# Create your models here.

djangoModels/views.py
from django.shortcuts import render

from djangoModels.models import UserModel


# Create your views here.
def getUsers(request):
    users = UserModel.objects.all()

    # Passing arguments into url
    return render(request, "users.html", {"users": users})

djangoRoute/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from djangoRoute.models import *


# Create your views here.
def index(request):
    # method 2: return html files
    return render(request, "index-django-template.html")


def user_list(request):
    print("Getting all the users ...")
    users = UserModel.objects.all()
    print("Finished getting all users ...", users)

    # Passing arguments into url
    return render(request, "users.html", {"users": users})


def user_detail(request, user_id):
    print("Getting user information for ", user_id)
    user = UserModel.objects.get(pk=user_id)
    print("Finishe getting user information for ", user.name)

    # Passing argument into url
    return render(request, "user_detail.html", {"user": user})


def test(request, a, b):
    return HttpResponse(f'a:{a} - b:{b}')


'''
The following are examples of redirecting and reverse parsing through views
- redirect: used for redirecting from one url to another
- reverse: used to do reverse parsing
    - note that if you declared namespace, please specify from the reverse
'''


def my_redirect(request):
    # redirect to google site
    return redirect('https://www.google.com')


def redirect_to_user_list(request):
    return redirect('/djangoRoute/userlist/')


def redirect_to_user_detail(request):
    # use reverse parsing here, note that we use namespace here
    # this is because we have declared the namespace in the djangoProject1
    # return redirect(reverse('djangoRoute:userdetail', args=(2,)))

    # another way of passing in the argument through keyword
    return redirect(reverse('djangoRoute:userdetail', kwargs={'user_id': 2}))

djangoTemplate/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def djangoTemplateIndex(request):
    data = {
        "name": "chunyue",
        "age": 25,
        "hobbies": ["chess", "swimming", "coding"],
        "address": {"city": "seattle", "state": "WA"},
        "foobar": [["1", "2", "3"],
                   ["4", "5", "6"],
                   ["7", "8", "9"]],
        "datetime": datetime.datetime.now()
    }
    return render(request, "index-django-template.html", data)

demo1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Demo 1</title>
</head>
<body>
    <h1>Hello From Django</h1>
</body>
</html>

djangoModels/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Users</title>
</head>
<body>
    <h1>Here are all the users: </h1>
    <ul>
        {% for user in users %}
            <li>{{ user.name}} - {{ user.age}}</li>
        {% endfor %}
    </ul>

</body>
</html>

djangoRoute/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Learning</title>
</head>
<body>
    <h1>Hello From Django</h1>
    <h2>Main Page</h2>

    {# url routing #}
    <a href="/djangoRoute/userlist/">Method 1: Use url to enter the user list page</a>

    <br>

    {# 反向解析 (Not compatible if you have the namespace turned on) #}
    {# <a href="{% url 'userlist' %}">Method 2: 反向解析 to enter the user list page</a> #}


    <br>

    {# 反向解析 with namespace #}
    <a href="{% url 'djangoRoute:userlist' %}">Method 3: 反向解析(with namespace) to enter the user list page</a>

</body>
</html>

djangoRoute/templates/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Learning</title>
</head>
<body>
    <h1>{{user.name}}'s information</h1>
</body>
</html>

djangoRoute/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Learning</title>
</head>
<body>
    <h1>All User List: </h1>
    <hr>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'djangoRoute:userdetail' user.id %}">
                {{ user.name}} - {{ user.age}}
            </a></li>
        {% endfor %}
    </ul>
</body>
</html>

djangoTemplate/templates/index-django-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Template</title>
</head>
<body>
    <h1>Django Template Page</h1>
    <hr>

    {# single line comment #}

    {% comment %}
        multiple lines comments
    {% endcomment %}

    <!-- Use of variables -->
    <p>Name: {{ name }}</p>
    <p>Age: {{ age }}</p>
    <p>All hobbies: {{ hobbies }}</p>
    <p>First hobby: {{ hobbies.0 }}</p>
    <p>Address: {{ address }}</p>
    <p>City: {{ address.city }}</p>
    <p>State: {{ address.state }}</p>


    <!-- Use of tags -->
    {% if age < 18 %}
        <p>{{ name }} is underage</p>
    {% else %}
        <p>{{ name }} is NOT underage</p>
    {% endif %}


    {% if age < 18 %}
        <p>{{ name }} is a baby </p>
    {% elif age < 45 %}
        <p>{{ name }} is young adult </p>
    {% else %}
        <p>{{ name }} is full adult </p>
    {% endif %}

    {% if address.city == 'seattle' and address.state == 'WA' %}
        <p>{{ name }} is in Seattle</p>
    {% else %}
        <p>{{ name }} is NOT in Seattle</p>
    {% endif %}

    <p>{{ name }}'s hobbies</p>
    {% for hobby in hobbies %}
        <li>{{ hobby }}</li>

        {% if forloop.first %}
            <b> -first hobby </b>
        {% endif %}

        {% if forloop.last %}
            <b> -last hobby </b>
        {% endif %}
    {% endfor %}

    <table border="1" width="300">
        {% for foo in foobar %}
            <tr>
                {% for bar in foo %}
                    <td>
                        {{ bar }} -- {{forloop.parentloop.counter}} -- {{ forloop.counter }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>

    <h4>Use of filters</h4>
    <p>age = {{ age }}</p>
    <p>two years later, age = {{ age|add:2}} </p>
    <p>two years before, age = {{ age|add:-2}} </p>

    <p>name = {{ name }}</p>
    <p>first char uppercase = {{ name|first|upper }}</p>
    <p>last char lowercase = {{ name|last|lower }}</p>
    <p>name.title = {{ name|title }}</p>

    <p>hobbies = {{ hobbies }}</p>
    <p>{{ hobbies|join:'+' }}</p>

    <p>datetime = {{ datetime }}</p>
    <p>datetime formatted = {{ datetime|date:'y-m-d' }}</p>
    <p>datetime formatted = {{ datetime|date:'Y-m-d' }}</p>

</body>
</html>